version: '3'
services:
  pwn:
    container_name: pwn
    build: .
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - "23946:23946"
    volumes:
      - type: bind
        source: ./ctf
        target: /ctf/work
