version: "3"
services:
  pwn:
    container_name: pwn
    build: .
    tty: true
    stdin_open: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - 8888:8888
      - 23946:23946
    volumes:
      - type: bind
        source: ./ctf
        target: /ctf/work
